name: safesync
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter_svg: ^2.0.5
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.3.2
  shared_preferences: ^2.0.13
  google_nav_bar: ^5.0.6
  any_animated_button: ^0.0.4
  multi_select_flutter: ^4.0.0
  http: ^1.2.1
  location: ^7.0.0 # Updated version
  latlong2: ^0.9.0
  cupertino_icons: ^1.0.2
  flutter_map: ^7.0.2 # Updated version
  image_picker: ^1.1.2 # Updated version
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # Updated lints

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo - splashscreen.png
    - assets/images/logo - loginpage.png
    - assets/images/logo - application.png
    - assets/images/logo - splash.svg
    - assets/images/background - loginpage.png
    - assets/images/background - design1.png
    - assets/images/background - design2.png
    - assets/images/background - design3.png
    - assets/images/background - design4.png
    - assets/images/logo - btao.png
    - assets/images/logo-safesyncwname.png
    - assets/images/logo-safesyncwnamelndscp.png
    - assets/images/logo-safesyncwhite.png
    - assets/images/logo-safesyncblue.png

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Light.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-Bold.ttf
